package com.muedsa.intellij.textReader.config;

public enum ConfigKey {
    FONT_FAMILY,
    FONT_SIZE,
    LINE_SPACE,
    FIRST_LINE_INDENT,
    PARAGRAPH_SPACE,
    MAX_TITLE_LINE_SIZE,
    READER_LINE_SIZE,
    SHOW_READER_LINE_TYPE,
    READER_LINE_COLOR,
    EDITOR_BACKGROUND_OFFSET_TYPE,
    EDITOR_BACKGROUND_OFFSET_X,
    EDITOR_BACKGROUND_OFFSET_Y
}
